### ISSUE TITLE
geomodelgrids_query tests data

### ISSUE THREAD

**Issue by pjm-usc** [baagaard-usgs/geomodelgrids#132]
I am trying to run the geomodelgrids_query tests, documented below.
I'm using a linux binary distribution installed on a current ubuntu version.
The executables appear to be running correctly...

gmgkuser@ed367f602a41:/opt/src/geomodelgrids-1.0.0rc2-Linux_x86_64$ geomodelgrids_info --help
Usage: geomodelgrids_info [--help] --models=FILE_0,...,FILE_M [--description] [--coordsys] [--values] [--blocks] [--all] [--verify]

    --help                       Print help information to stdout and exit.
    --models=FILE_0,...,FILE_M   Models to query (in order).
    --description                Display model description.
    --coordsys                   Display model coordinate system.
    --values                     Display names and units of values stored in the model.
    --blocks                     Display description of blocks.
    --all                        Display description, coordinate system, values, and blocks
    --verify                     Verify model conforms to GeoModelGrids specifications. 

So next step is to run the examples for geomodelgrids_query. I looked at the examples, but I don't see the input files "one-block-flat_latlon.in" mentioned.

If I create this file, and put it in the tests/data directory, the query runs, but I get an outputfile with only the contents of my query, and non-

```
gmgkuser@ed367f602a41:/opt/src/geomodelgrids-1.0.0rc2-Linux_x86_64/src$ geomodelgrids_query --models=tests/data/one-block-flat.h5 --points=tests/data/one-block-flat_utm.in --output=tests/data/one-block-flat_utm.out --values=one,two --points-coordsys=EPSG:26910

gmgkuser@ed367f602a41:/opt/src/geomodelgrids-1.0.0rc2-Linux_x86_64/src/tests/data$ more *.out
::::::::::::::
one-block-flat_latlon.out
::::::::::::::
# geomodelgrids_query --models=tests/data/one-block-flat.h5 --points=tests/data/one-block-flat_latlon.in --output=tests/data/one-block-flat_latlon.out --values=two
#           x0            x1            x2           two
::::::::::::::
```

The examples I am trying to run are below. Thanks for suggestions on how to get these examples to run successfully.

## Examples

The input files for these examples are located in `tests/data`.

### Query with input points in WGS84

Query the model `one-block-flat.h5` for a single value `two` at three points given in file `one-block-flat_latlon.in` with the output written to file `one-block-flat_latlon.out`. We use the default coordinate system for the input points, which is latitude, longitude, elevation with the WGS84 horizontal datum and meters above the ellipsoid for the vertical datum.

```bash
geomodelgrids_query \
--models=tests/data/one-block-flat.h5 \
--points=tests/data/one-block-flat_latlon.in \
--output=tests/data/one-block-flat_latlon.out \
--values=two

# Input: one-block-flat_latlon.in
37.455  -121.941   0.0
37.479  -121.734  -5.0e+3
37.381  -121.581  -3.0e+3

# Output: one-block-flat_latlon.out, latitude (deg), longitude (deg), elevation (m), two (m/s)
# geomodelgrids_query --models=one-block-flat.h5 --points=one-block-flat_latlon.in --output=one-block-flat_latlon.out --values=two
#           x0            x1            x2           two
  3.745500e+01 -1.219410e+02  0.000000e+00 -1.520064e+03
  3.747900e+01 -1.217340e+02 -5.000000e+03  1.853648e+04
  3.738100e+01 -1.215810e+02 -3.000000e+03  7.266073e+03
```

**Comment by baagaard-usgs** [comment]
I see that the Makefile.am file is missing some of the test data files, which results in these files being left out of the source and binary distributions. I will fix that and do some additional testing of the binary. Thanks for reporting this.

**Comment by pjm-usc** [comment]
Any thoughts on why no values are produced in the output file if I create the missing input file? The query seems to generate the output file, but the input points are not reported, and no material properties are reported.
geomodelgrids_info seems to find the model ok:
geomodelgrids_info --models=tests/data/one-block-flat.h5 --all
Model: tests/data/one-block-flat.h5
    Verification
        Verifying metadata...OK
        Verifying model coordinate system ...OK
        Verifying block 'block'...OK
        Verifying blocks span vertical dimension of domain...OK


But after creating the expected input file, no results are reported in the output file


gmgkuser@0a9c52b0f0d1:/opt/src/geomodelgrids-1.0.0rc2-Linux_x86_64/src$ geomodelgrids_query \
--models=tests/data/one-block-flat.h5 \
--points=tests/data/one-block-flat_latlon.in \
--output=tests/data/one-block-flat_latlon.out \
--values=two

gmgkuser@0a9c52b0f0d1:/opt/src/geomodelgrids-1.0.0rc2-Linux_x86_64/src$ cat tests/data/one-block-flat_latlon.out
# geomodelgrids_query --models=tests/data/one-block-flat.h5 --points=tests/data/one-block-flat_latlon.in --output=tests/data/one-block-flat_latlon.out --values=two
#           x0            x1            x2           two

**Comment by baagaard-usgs** [comment]
I uploaded new tarballs that add the missing test data files. I was able to run the example and get the expected output using the new tarball.

Before your run `source setup.sh` make sure your PATH is set to the minimal system directories (for example, `PATH=/usr/bin:/bin:/usr/sbin:/sbin`) and LD_LIBRARY_PATH is not set. There could be other software that is interfering.
