### ISSUE TITLE
Reading .2grd files from EarthVision

### ISSUE THREAD

**Issue by ahinoamp** [baagaard-usgs/geomodelgrids#136]
Hi Brad,

I have perhaps a simple question that is only tangentially related to this code you've written.
I have a .2grd file from EarthVision that I'd like to transform to a format readable by other general softwares (ply, stl, vtk, etc.). 
Do you know where I can find info about the structure of that binary file and how to read it?

Thanks for your help!

Noe

**Comment by baagaard-usgs** [comment]
I am not aware of any openly available specification for .2grd files. I believe EarthVision may provide a translator to convert a .2rgd file to a tsurf file (which is an ASCII format that GoCad uses).

**Comment by ahinoamp** [comment]
Thanks Brad!
